[package]
name = "ebr_aba_protection"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-epoch = "0.9"
crossbeam-utils = "0.8"
rand = "0.8"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "concurrent_benchmarks"
harness = false
